import 'guide_answer_service.dart';

class AskAiService {
  static Future<String> askGuideQuestion({
    required String guideTitle,
    required String guideContent,
    required String userMessage,
    List<String> recentQuestions = const [],
  }) async {
    // We intentionally do NOT require any external AI endpoint.
    // Answers are generated by searching and summarizing the guide content locally.
    return GuideAnswerService.answerFromGuide(
      guideTitle: guideTitle,
      guideContent: guideContent,
      userMessage: userMessage,
    );
  }
}
